controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

security_domain:
    resource: 'routes/domains/security.yaml'

hunt_domain:
    resource: 'routes/domains/hunt.yaml'

admin_bears_domain:
    resource: 'routes/domains/admin-bears.yaml'