admin_bear_all:
  path:
    - '/api/admin/bear/'
  methods: GET
  defaults:
    _controller: App\Controller\AdminBearController::fetchAllAction

admin_bear_create:
  path:
    - '/api/admin/bear/create'
  methods: POST
  defaults:
    _controller: App\Controller\AdminBearController::createBearAction

admin_bear_fetch:
  path:
    - '/api/admin/bear/{id}'
  methods: GET
  defaults:
    _controller: App\Controller\AdminBearController::fetchBearAction

admin_bear_update:
  path:
    - '/api/admin/bear/{id}'
  methods: PUT
  defaults:
    _controller: App\Controller\AdminBearController::updateBearAction

admin_bear_delete:
  path:
    - '/api/admin/bear/{id}'
  methods: DELETE
  defaults:
    _controller: App\Controller\AdminBearController::deleteBearAction