bears_all:
  path:
    - '/api/bears'
  methods: GET
  defaults:
    _controller: App\Controller\BearController::fetchAllAction

bears_find_one:
  path:
    - '/api/bears/location'
  methods: POST
  defaults:
    _controller: App\Controller\BearController::fetchBearByLocation