bear_fetch_all:
  path:
    - '/api/bear/'
  methods: GET
  defaults:
    _controller: App\Controller\BearController::fetchAllAction

bear_create:
  path:
    - '/api/bear/create'
  methods: POST
  defaults:
    _controller: App\Controller\BearController::createBearAction

bear_fetch_one:
  path:
    - '/api/bear/{id}'
  methods: GET
  defaults:
    _controller: App\Controller\BearController::fetchBearAction

bear_update:
  path:
    - '/api/bear/{id}'
  methods: PUT
  defaults:
    _controller: App\Controller\BearController::updateBearAction

bear_delete:
  path:
    - '/api/bear/{id}'
  methods: DELETE
  defaults:
    _controller: App\Controller\BearController::deleteBearAction