user_create:
  path:
    - '/api/user/create'
  methods: POST
  defaults:
    _controller: App\Controller\UserController::createUserAction

user_fetch_all:
  path:
    - '/api/user/'
  methods: GET
  defaults:
    _controller: App\Controller\UserController::fetchAllAction